---
- name: Create log directory
  file:
    path: /var/log/nginx
    state: directory
  become: yes

- name: install nginx
  apt:
    name: nginx
    state: latest
  become: yes
  notify:
    restart: nginx

- name: configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
  become: yes

- name: delete default sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: delete default sites-available
  file:
    state: absent
    path: /etc/nginx/sites-available/default
  become: yes

