---
- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  become: yes
  become_user: root

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo
  become: yes

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  become: yes

- name: install npm
  apt:
    name: npm
  become: yes

- name: install nodejs legacy
  apt:
    name: nodejs-legacy
  become: yes

- name: install configurable-http-proxy
  npm:
    name: configurable-http-proxy
    global: yes
    state: latest
  become: yes

- name: install notebook
  pip:
    name: notebook
    executable: /usr/bin/pip3
  become: yes

- name: install jupyterhub
  pip:
    name: jupyterhub
    executable: /usr/bin/pip3
  become: yes

- name: install oauthenticator
  pip:
    name: oauthenticator
    executable: /usr/bin/pip3
  become: yes

- name: install sudospawner
  pip:
    name: sudospawner
    executable: /usr/bin/pip3
  become: yes
