---
- name: ensure fail2ban is installed
  apt:
    pkg: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
  notify:
    - restart fail2ban

- name: ensure fail2ban is configured
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  become: yes
  notify:
    - restart fail2ban

- name: ensure fail2ban starts on a fresh reboot
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: yes
