---
- name: "FIX: Stupid server doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  become: true

- name: install vim
  apt:
    name: vim
    state: latest
  become: yes

- name: Update packages list
  apt: update_cache=yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: Upgrade packages
  apt:
    upgrade: safe
  become: yes
  when: ansible_os_family == 'Debian'

- name: Check what the new version is
  shell:  lsb_release -r | awk '{print $2}'
  changed_when: False
  register: new_release

- name: Notify distribution version upgrade
  debug: msg="Debian has been upgraded from {{ ansible_lsb.release }} to {{ new_release.stdout }}"
  when: ansible_lsb.release != new_release.stdout

- name: List services to restart (1/2)
  shell: checkrestart | grep ^service | awk '{print $2}'
  register: services
  changed_when: False
  when: ansible_os_family == 'Debian'

- name: List services to restart (2/2)
  debug: msg="{{ /services.stdout_lines | count }} services to restart ({{ services.stdout_lines | join (', ') }})"
  when: (ansible_os_family == 'Debian' and services.stdout_lines)

- name: install git
  apt:
    name=git
    state=latest
  become: yes

- include: ssh.yml
- include: python.yml

