---
- fail: msg="no ssh keys defined"
  when: github_usernames == [] and other_ssh_keys == []

- name: sshd configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=0644
  sudo: yes
  notify:
  - restart sshd

- name: directory to hold public keys
  file: state=directory path=/tmp/pubkeys mode=0755
  tags:
    - ssh

- name: fetch public keys from github
  get_url:
    dest: "/tmp/pubkeys/{{ item }}-pubkeys"
    url: "https://github.com/{{ item }}.keys"
    force: yes
  with_items: "{{ github_usernames }}"
  tags:
    - ssh

- name: .ssh directory in home dir
  file:
    state: directory
    path: "{{ home_path }}/.ssh"
    mode: 0755
  tags:
    - ssh

- name: assemble the authorized keys file
  assemble:
    src: /tmp/pubkeys
    dest: "{{ home_path }}/.ssh/authorized_keys"
    mode: 0600
  become: yes
  tags:
    - ssh
